### ISSUE TITLE
thread 'main' panicked at 'Sqlite doesn't support multiple alter options'

### ISSUE THREAD

**Issue by TheBlindM** [SeaQL/sea-orm#1809]
## Description
thread 'main' panicked at 'Sqlite doesn't support multiple alter options'
```
warning: `app` (bin "app") generated 4 warnings (run `cargo fix --bin "app"` to apply 3 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 0.99s
     Running `target\debug\app.exe`
thread 'main' panicked at 'Sqlite doesn't support multiple alter options', C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-query-0.30.0\src\backend\sqlite\table.rs:119:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: sea_query::backend::sqlite::table::impl$0::prepare_table_alter_statement
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-query-0.30.0\src\backend\sqlite\table.rs:119
   3: sea_query::table::alter::impl$9::build<sea_query::backend::sqlite::SqliteQueryBuilder>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-query-0.30.0\src\table\alter.rs:382
   4: sea_query::table::alter::TableAlterStatement::build<sea_query::backend::sqlite::SqliteQueryBuilder>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-query-0.30.0\src\table\alter.rs:378
   5: sea_orm::database::statement::impl$12::build
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-orm-0.12.2\src\database\statement.rs:116
   6: sea_orm::database::db_connection::DatabaseBackend::build<sea_query::table::alter::TableAlterStatement>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-orm-0.12.2\src\database\db_connection.rs:489
   7: sea_orm_migration::manager::impl$0::exec_stmt::async_fn$0<sea_query::table::alter::TableAlterStatement>
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-orm-migration-0.12.2\src\manager.rs:31
   8: sea_orm_migration::manager::impl$2::alter_table::async_fn$0
             at C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-orm-migration-0.12.2\src\manager.rs:65
   9: migration::m20220101_000003_alert_ssh_session::impl$1::up::async_block$0
             at .\migration\src\m20220101_000003_alert_ssh_session.rs:21
```

## Steps to Reproduce
1.
```
pub use sea_orm_migration::prelude::*;

mod m20220101_000001_create_ssh_session;
mod m20220101_000001_create_session;
mod m20220101_000001_create_group;
mod m20220101_000002_alert_ssh_session;
mod m20220101_000003_alert_ssh_session;

pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
	fn migrations() -> Vec<Box<dyn MigrationTrait>> {
		vec![
			Box::new(m20220101_000001_create_ssh_session::Migration),
			Box::new(m20220101_000001_create_group::Migration),
			Box::new(m20220101_000001_create_session::Migration),
			Box::new(m20220101_000003_alert_ssh_session::Migration),
		]
	}
}

```
2. m20220101_000001_create_ssh_session.rs
```
use std::future;

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.create_table(
				Table::create()
					.table(SshSession::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(SshSession::Id)
							.integer()
							.not_null()
							.auto_increment()
							.primary_key(),
					)
					.col(ColumnDef::new(SshSession::ProxyType).integer().not_null())
					.col(ColumnDef::new(SshSession::TtyType).string().not_null())
					.col(ColumnDef::new(SshSession::SessionId).integer().not_null())
					.col(ColumnDef::new(SshSession::Ip).string().not_null())
					.col(ColumnDef::new(SshSession::Port).string().not_null())
					.col(ColumnDef::new(SshSession::Username).string().not_null())
					.col(ColumnDef::new(SshSession::Pwd).string())
					.col(ColumnDef::new(SshSession::PrivateKeyFile).string())
					.col(ColumnDef::new(SshSession::Passphrase).string())
					.col(ColumnDef::new(SshSession::HttpProxyHost).string())
					.col(ColumnDef::new(SshSession::HttpProxyPort).string())
					.col(ColumnDef::new(SshSession::SocketProxyHost).string())
					.col(ColumnDef::new(SshSession::SocketProxyPort).string())
					.col(ColumnDef::new(SshSession::TenantId).string().not_null())
					.to_owned(),
			).await
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		// Replace the sample below with your own migration scripts
		manager
			.drop_table(Table::drop().table(Session::Table).to_owned())
			.await
	}
}

/// Learn more at https://docs.rs/sea-query#iden
#[derive(Iden)]
enum Session {
	Table,
	Id,
	SessionName,
	Type,
}

#[derive(Iden)]
enum SshSession {
	Table,
	Id,
	TtyType,
	SessionId,
	Ip,
	Port,
	Username,
	Pwd,
	PrivateKeyFile,
	Passphrase,
	HttpProxyHost,
	HttpProxyPort,
	SocketProxyHost,
	SocketProxyPort,
	AuthType,
	ProxyType,
	TenantId
}

#[derive(Iden)]
enum LocalSession {
	Table,
	Id,
	Type,
	SessionId,
}

#[derive(Iden)]
enum RedisSession {
	Table,
	Id,
	SessionId,
}

```

3.m20220101_000003_alert_ssh_session.rs
```
use std::future;

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {

		manager
			.alter_table(
				Table::alter()
					.table(SshSession::Table)
					.add_column_if_not_exists(ColumnDef::new(SshSession::Forwards).json())
					.add_column_if_not_exists(ColumnDef::new(SshSession::X11).boolean())
					.add_column_if_not_exists(ColumnDef::new(SshSession::AgentForward).boolean())
					.add_column_if_not_exists(ColumnDef::new(SshSession::ReadyTimeout).integer())
					.to_owned(),
			).await


	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		// Replace the sample below with your own migration scripts
		manager
			.drop_table(Table::drop().table(SshSession::Table).to_owned())
			.await
	}
}

#[derive(Iden)]
enum SshSession {
	Table,
	Forwards,
	X11,
	AgentForward,
	ReadyTimeout,
}

```

## Versions
sea-orm = "^0"

**Comment by IgnisDa** [comment]
I suggest you add a `if !manager.has_column("ssh_session", "<column_name>")` before your alter stmt.

**Comment by TheBlindM** [comment]
> I suggest you add a `if !manager.has_column("ssh_session", "<column_name>")` before your alter stmt.

Sorry, could you be more detailed?

**Comment by IgnisDa** [comment]
```rs
use sea_orm::EntityTrait;
use sea_orm_migration::prelude::*;

use super::m20230622_create_exercise::Exercise;
use crate::entities::prelude::Exercise as ExerciseModel;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20230814_add_lot_field_to_exercise"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        if !manager.has_column("exercise", "lot").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(Exercise::Table)
                        .add_column(ColumnDef::new(Exercise::Lot).string_len(2).not_null())
                        .to_owned(),
                )
                .await?;
        }
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
```

**Comment by TheBlindM** [comment]
> ```rust
> use sea_orm::EntityTrait;
> use sea_orm_migration::prelude::*;
> 
> use super::m20230622_create_exercise::Exercise;
> use crate::entities::prelude::Exercise as ExerciseModel;
> 
> pub struct Migration;
> 
> impl MigrationName for Migration {
>     fn name(&self) -> &str {
>         "m20230814_add_lot_field_to_exercise"
>     }
> }
> 
> #[async_trait::async_trait]
> impl MigrationTrait for Migration {
>     async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
>         if !manager.has_column("exercise", "lot").await? {
>             manager
>                 .alter_table(
>                     Table::alter()
>                         .table(Exercise::Table)
>                         .add_column(ColumnDef::new(Exercise::Lot).string_len(2).not_null())
>                         .to_owned(),
>                 )
>                 .await?;
>         }
>         Ok(())
>     }
> 
>     async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
>         Ok(())
>     }
> }
> ```

So I have multiple columns to add, do I need to add a 'has_column' before each one?

**Comment by IgnisDa** [comment]
yes thats what I do: https://github.com/IgnisDa/ryot/pull/262/commits/c716bcc59de7535d58fbf53e21db280d8035e82d#diff-a2f47312e6265b8f02bd1bf8003a335008ae2683048e2f9d133bc985f3fcc84d

**Comment by TheBlindM** [comment]
> yes thats what I do: [IgnisDa/ryot@c716bcc#diff-a2f47312e6265b8f02bd1bf8003a335008ae2683048e2f9d133bc985f3fcc84d](https://github.com/IgnisDa/ryot/commit/c716bcc59de7535d58fbf53e21db280d8035e82d#diff-a2f47312e6265b8f02bd1bf8003a335008ae2683048e2f9d133bc985f3fcc84d)

Isn't 'add_column_if_not_exists' meaningless?

**Comment by IgnisDa** [comment]
Yes, it is meaningless if put inside the if stmt, so I have not used it.
