### ISSUE TITLE
`Number exceeds maximum value that can be represented.`

### ISSUE THREAD

**Issue by gitmalong** [SeaQL/sea-orm#1942]
Hi!

I am inserting my `Option<rust_decimal::Decimal>` via the code below while `volume` is of type `Decimal`.

```rust
entities::prelude::MyEntity::update_many()
            .col_expr(
                ledger::Column::Volume,
                Expr::value(Value::Decimal(Some(volume.into()))),
            )
```

which works fine.

But when reading rows from the table the app panics with

```rust
thread 'tokio-runtime-worker' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust_decimal-1.32.0/src/decimal.rs:470:23:
Number exceeds maximum value that can be represented.
stack backtrace:
15:        0x10500b984 - core::panicking::panic_fmt::h3fc5ad127547e2b3
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:72:14
  16:        0x1050085f0 - rust_decimal::decimal::Decimal::from_i128_with_scale::panic_cold_display::hfd9e6ce1ee2cd10e
  17:        0x104f9698c - rust_decimal::decimal::Decimal::from_i128_with_scale::h6c1a00be0be3d92e
  18:        0x104d7f60c - sqlx_postgres::types::rust_decimal::<impl core::convert::TryFrom<sqlx_postgres::types::numeric::PgNumeric> for rust_decimal::decimal::Decimal>::try_from::hc52b6925820be2f8
  19:        0x104d7f9e8 - sqlx_postgres::types::rust_decimal::<impl sqlx_core::decode::Decode<sqlx_postgres::database::Postgres> for rust_decimal::decimal::Decimal>::decode::hd9a3478e707acc77
  20:        0x104c139c4 - sqlx_core::row::Row::try_get::he57137519c5b9ff8
  21:        0x104c121cc - sea_orm::executor::query::TryGetable::try_get::hf252a8b61b7be3c3
  22:        0x104c1907c - sea_orm::executor::query::QueryResult::try_get::h13b7f2f1363a1537
  23:        0x104be2ab4 - <myapp::entities::ledger::Model as sea_orm::entity::model::FromQueryResult>::from_query_result::h3b4523db16e761a2
```

**Comment by gitmalong** [comment]
Seems to be an issue on sqlx side: https://github.com/launchbadge/sqlx/issues/666

**Comment by tyt2y3** [comment]
1. Are you sure your database table or your select expression does not yield a value that exceeds the valid range? If so, this is a bug in the protocol decode phase
2. Otherwise, you can use BigDecimal, if your value exceeds the range of Decimal

**Comment by gitmalong** [comment]
1. Yes, I only inserted data via my SeaORM app and all inserts/updates (I just have two) use the `Decimal` type. Therefore it must be within a valid range.

**Comment by tyt2y3** [comment]
> Therefore it must be within a valid range.

Can you verify that?
